[package]
name = "orderbook-rpc"
version = "2.0.0"
edition = "2018"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
description = "A pallet that nft orders management"
license = "GPL-3.0-or-later"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0" }
jsonrpc-core = "15.0"
jsonrpc-core-client = "15.0"
jsonrpc-derive = "15.0"
serde = { version = "1.0", features = ["derive"], optional = true }

# Substrate packages

sp-api = { version = '2.0.0', default-features = false }
sp-blockchain = { version = '2.0.0', default-features = false}
sp-rpc = { version = '2.0.0', default-features = false}
sp-runtime = { version = '2.0.0', default-features = false}

# local packages

orderbook-runtime-api = { version = "2.0.0", path = "../runtime-api", default-features = false }

[dependencies.orderbook]
default-features = false
package = 'pallet-orderbook'
path = '..'
version = '2.0.0'

[features]
default = ["std"]
std = [
  "serde",
  "sp-api/std",
  "sp-runtime/std",
  "orderbook-runtime-api/std",
  "orderbook/std"
]
